# Promise 이해하기

javascript를 다루다 보면 많은 함수에서 promise 객체를 리턴하는 걸 볼 수 있습니다.
이 Promise는 비동기 작업을 처리할 때 사용합니다.
Promise를 직접 구현해보면서 javascript 언어의 기초 문법과 비동기 처리 과정을 이해해보고자 합니다.

코드는 프로미스의 이해를 위해 구현한 멘탈 모델로, 실제 native promise의 구현체와는 다르다는 점을 미리 말씀드립니다.
javascript를 전혀 모르는 사람도 이해할 수 있도록 기초부터 작성하였습니다.

아주 간단한 Promise와 비동기를 처리하는 Promise 이 두 가지 버전을 순서대로 진행합니다.

## 1. 아주 간단한 Promise를 구현해보면서 javascript 기본 이해하기

```js
class MyPromise {
  constructor(constructorCallback) {
    // console.log("[*] log constructorCallback(): " + constructorCallback.toString());
    constructorCallback((value) => {
      this.value = value;
    });
  }
  
  then(thenCallback) {
    thenCallback(this.value);
  }
}

function start() {
  return new MyPromise((myfunc) => {
    // console.log("[*] log myfunc(): " + myfunc.toString());
    myfunc('javascript');
  });
}

start()
  .then((result) => {
    console.log(result)
  }); // 출력: javascript
```

**start()는 MyPromise의 객체를 리턴하여 MyPromise의 then() 메서드를 호출하는데 then() 메서드의 result 파라미터로 넘어온 'javascript'를 출력하여 모든 코드 실행이 끝납니다.**

이 코드가 자연스럽게 이해된다면 두 번째 Promise 구현 부분으로 넘어가시면 됩니다.

----

### 1.1 Javascript에서의 함수

자세한 설명을 시작하겠습니다.
JS에서는 함수는 굉장히 특별하게 취급받습니다. 함수 자체를 다른 함수의 인자로 넘길 수 있고 함수 자체를 리턴할 수도 있습니다. JAVA에서는 불가능한 일입니다.

이어서 함수와 관련된 생소한 형태에 대해서 살펴보겠습니다.

`() => {}` 이러한 형식이 많이 보이는데 이는 [arrow function](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions), 화살표 함수라고 합니다. 인자는 () 소괄호에 안에 위치하고, {} 블럭 안의 내용을 수행합니다.

```js
const printText = (text) => {
  console.log(text);
};
```

```js
function printText(text) {
  console.log(text);
}
```

두 함수 모두 text를 인자로 받아서 콘솔에 출력하는 printText 함수입니다.
두 선언 방식의 차이점에 대해 간략히 설명하면, const 형태의 arrow function은 hoisting을 지원하지 않기 때문에 호출되기 전에 선언되어야 한다는 것입니다.
그럼에도 arrow function을 사용하는 이유는 함수형 프로그래밍 방식이기 때문입니다.

### 1.2 callback function

다시 이해하고자 하는 코드로 돌아가봅시다. 이 코드에는 callback function의 개념이 숨겨져 있어서 JS를 처음본다면 굉장히 이해하기 어렵습니다. 콜백 함수란 간단히 말해 "나중에 호출된다"는 뜻입니다.

```js
function A() {
  console.log('a');
}

function B(callback) {
  callback();
}

B(A); // 출력: a
```
함수 A가 함수 B의 인자 값으로 전달되어 함수 B 안에서 함수 A가 호출된다면 이 맥락에서 함수 A는 callback function입니다.

callback 함수가 어떻게 인자로 전달되고 어떻게 호출되었는지 MyPromise에서 천천히 살펴보겠습니다.

new 키워드를 사용해 MyPromise의 객체를 생성할 때 생성자가 호출됩니다.

```js
(myfunc) => {
  myfunc('javascript');
}
```

이 함수가 생성자의 인자인 constructorCallback에 전달됩니다.

다음 줄에서 바로 constructorCallback을 호출하는데, 이 함수는 위에 보시다시피 함수를 myfunc이라는 파라미터로 받아서 바로 실행하는데, 'javascript'를 인자로 실행합니다.

```js
(value) => {
  this.value = value;
}
```

즉, 위 함수에서 'javascript'가 value라는 파라미터로 전달되어 실행되었습니다.

this 키워드를 사용해서 생성된 객체의 멤버 변수로 사용할 수 있습니다. 생성된 객체의 멤버 변수인 this.value에 'javascript' 문자열을 저장하게 되었습니다.

드디어 start()의 MyPromise 생성을 마치고 MyPromise의 객체를 리턴했습니다.

then 부분을 살펴보겠습니다. then 부분은 쉽습니다. 앞선 과정으로 this.value 라는 멤버 변수에 'javascript'가 저장되어 있습니다. '.' (dot) 으로 멤버 변수에 접근하듯이 class의 메서드도 '.' 으로 접근할 수 있습니다.

```js
class MyPromise {
  // ...
  then(thenCallback) {
    thenCallback(this.value);
  }
}

start()
  .then((result) => {
    console.log(result)
  }); // 출력: javascript
```

MyPromise에 선언되어 있는 then은 thenCallback라는 파라미터를 가지고 있습니다. 위 코드에서는 thenCallback에 아래의 함수가 전달됩니다.

```js
(result) => {
  console.log(result)
}
```

callback 함수 thenCallback을 바로 다음 줄에서 실행하는데 파라미터가 'javascript'가 저장되어 있는 this.value 이므로 result에 'javascript'가 인자로 전달되어 'javascript'가 출력됩니다.

아직 Promise가 무엇인지 잘 모르겠지만 콜백 함수는 이해하게 되었습니다. 🎉

## 2. 비동기 개념을 추가해 Promise 구현하기

### 2.1 요구사항

- 비동기 작업이 resolve (성공)하면 then으로 전달한 함수가 실행됩니다.
- 비동기 작업이 reject (실패)하면 catch로 받을 수 있습니다.

MyPromise 라는 class를 만들고 생성자, resolve(), reject(), then(), catch() 함수를 작성했습니다.

### 2.2 promise의 상태

Promise의 상태에는 3가지 종류가 있습니다.

대기(pending): 이행하거나 거부되지 않은 초기 상태
이행(fulfilled): 연산이 성공적으로 완료한 상태
거부(rejected): 연산이 실패한 상태

비동기 작업을 수행 중일 때는 pending이고 비동기 작업이 끝난 후 성공, 실패에 따라 fulfilled, rejected 상태가 되고 또 각각의 상태에 따라 then, catch가 실행됩니다.

### 2.3 소스 코드

아래 코드는 비동기 promise 코드 전문입니다. 이 코드를 바탕으로 3에서 비동기와 관련된 핵심 개념을 설명하고 4에서 코드의 흐름을 설명하였습니다.

```js
// Waits for the given duration.
const delay = (durationInMillis) => {
  return new MyPromise((resolve, reject) => { 
    process.stdout.write("MyPromise 생성자에 넘기는 콜백 함수에서 ");
    if (durationInMillis < 0) {
      console.log("reject() 실행 시점을 지금 바로로 지정");
      reject(
        new Error(`Duration cannot be less than 0 but given ${durationInMillis}.`)
      );
      return;
    }
    console.log("resolve() 실행 시점을 " + durationInMillis + "ms 후로 지정");
    setTimeout(() => {
      resolve();
    }, durationInMillis);
  });
};

class MyPromise {
  constructor(callback) {
    console.log("MyPromise 생성자 실행");
    this.callbackWhenResolved = null;
    this.callbackWhenCaught = null;

    setTimeout(() => {
      callback(
        (value) => {
          this.resolve(value);
        },
        (value) => {
          this.reject(value);
        }
      )
    });
  }

  resolve(value) {
    console.log("3초 후 resolve() 실행되어 callback 함수가 실행됨");
    if (this.callbackWhenResolved) {
      this.callbackWhenResolved(value);
    }
  }

  reject(value) {
    console.log("reject() 실행해 callback 함수가 실행됨");
    if (this.callbackWhenCaught) {
      this.callbackWhenCaught(value);
    }
  }

  then(resolveCallback, rejectCallback) {
    console.log("then() 실행");
    console.log("this.callbackWhenResolved에 resolveCallback 등록");
    this.callbackWhenResolved = resolveCallback;
    if (rejectCallback) {
      console.log("this.callbackWhenCaught에 rejectCallback 등록");
      this.callbackWhenCaught = rejectCallback;
    }
    return this;
  }

  catch(callback) {
    console.log("catch() 실행");
    this.callbackWhenCaught = callback;
    return this;
  }
}

const someMethod = async () => {
  try {
    await delay(3000);
    console.log("delay(3000), 즉 3초 후 출력됨");
  } catch (delayError) {
    console.log(delayError);
  }
  return 3;
};

const wrongMethod = async () => {
  try {
    await delay(-500);
    console.log("error가 발생해 이 부분은 실행되지 않음");
  } catch (delayError) {
    console.log("wrongMethod()에서 error를 catch함");
    console.log(delayError);
  }
  return -5;
};

console.log("Start");
(async () => {
  console.log("return value: " + await wrongMethod());
  console.log("return value: " + await someMethod());
})();
```

## 3. 비동기: 개념, promise, async & await 사용법 이해하기

Promise의 핵심은 바로 '비동기'에 있습니다.

### 3.1 async, await

비동기를 코드로 이해하기 위해 async, await 키워드를 먼저 배워봅시다.

```js
(async () => {
  console.log(await someMethod());
})();
```

**await는 비동기 함수가 실행되고 결과를 받을 때까지 기다리라는 뜻**입니다. 이 말을 생각해보면 someMethod()가 비동기 함수임을 알 수 있습니다. 2.3 소스코드에서 확인해보면 someMethod()는 Promise를 반환하는 비동기 메서드입니다.

주의할 점은 **await 키워드는 Promise를 반환하는 비동기 함수 안에서만 작성할 수 있다**는 것입니다. 그래서 () => {} 함수 앞에 async 키워드를 붙여서 "이 함수는 비동기 함수다" 라고 알려준 것입니다. 

또 중요한 점은 **async 함수는 promise를 반환**한다는 것입니다.

### 3.2 async, await는 왜 사용할까요? 

async, await는 Promise를 사용하는 비동기 처리를 더 쉽게 사용하도록 도와줍니다. 비동기를 마치 동기처럼 실행하도록 해줍니다.

아직 Promise를 잘 모르기 때문에 Promise가 어떻게 사용되는 것인지, 비동기란 무엇인지 알아본 후에 위의 답을 다시 이해해보겠습니다.

### 3.3 promise

```js
someMethod()
  .then((result) => { // *
    console.log(result);
    return someMethod(); 
  })
  .then((result) => { // **
    console.log(result);
    return someMethod();
  })
  .then((result) => { // ***
    console.log(result);
  });
```
someMethod()를 3번 호출하면서 리턴 값이 3번 콘솔에 출력되는데 언제 출력되는지가 중요합니다.
함수 실행 -> 3초 후 출력 -> 출력 후 함수 실행 -> 3초 후 출력 -> 출력 후 함수 실행 -> 3초 후 출력
그래서 이 프로그램이 완료되기 위해서는 최소 9초의 시간이 걸립니다.

someMethod()는 Promise를 반환하는 비동기 메서드입니다. **Promise는 비동기 작업이 resolve(성공)하면 then() 로 return 값을 전달받아 처리할 수 있습니다.** someMethod() 에서는 3을 리턴합니다. // * 여기에서 then() 메서드가 3을 result 인자로 받아 콘솔에 3을 출력하고 다시 someMethod()을 리턴합니다.

### 3.4 promise chaining

promise.then을 한 번 호출했는데 또 then()이 붙어있습니다. promise.then을 호출하면 promise를 반환하기 때문입니다. 이를 Promise chaining 이라고 합니다. result가 .then 핸들러의 체인(사슬)을 통해 전달된다는 뜻입니다.

```js
class MyPromise {
  // ...  
  then(resolveCallback, rejectCallback) {
    console.log("then 실행");
    this.callbackWhenResolved = resolveCallback;
    if (rejectCallback) {
      this.callbackWhenCaught = rejectCallback;
    }
    return this;
  }
```

promise chaining과 관련해서 promise 구현 코드를 잠깐 보면, return this 즉 MyPromise 자체를 반환하고 있는 것을 확인할 수 있습니다. 따라서 현재 구현된 코드를 통해서도 체이닝이 가능합니다.

promise chaining은 순차적으로 처리해야 하는 비동기 작업이 여러 개 있을 때 사용할 수 있습니다.
만약 // * 에 있는 두 번째 someMethod()가 오류를 전달했다고 가정하면 promise를 성공해야 실행될 수 있는 then으로는 처리할 수 없기 때문에 콘솔에 3이 1번만 출력되고 // ** 이후로는 전부 실행이 되지 않습니다.

### 3.5 동기 비동기

동기란 요청 후 결과가 반환될 때까지 대기하고 있다가 결과를 받은 후 다음 요청을 수행하는 방식을 말합니다.
비동기란 요청 후 결과가 반환될 때까지 기다리지 않고 바로 다음 작업을 수행하는 방식을 말합니다.

비동기 개념이 생소하다면 "당연히 응답을 받은 후에 다음 명령이 실행되어야 하지 않을까?"라고 생각할 수 있습니다.

이해를 돕기 위해 동기 방식으로 실행해보았습니다.
```js
console.log(someMethod());
console.log(someMethod());
console.log(someMethod());
```

실행해보면 3이라는 리턴 값이 출력되지 않고 Promise object가 출력됩니다. 또한 9초가 아닌 3초 정도 후에 종료됩니다.

```
Promise { <pending> }
Promise { <pending> }
Promise { <pending> }
```

위 코드에서 someMethod() 로 비동기 작업을 요청만 하고 결과 값은 못 받은 채로 console.log()가 바로 수행됩니다. 이후 또 바로 두 번째 someMethod()가 실행됩니다. 역시나 요청만 하고 결과 값을 받지 않은 채로 console.log()가 수행합니다. 이후도 같습니다.

```
Promise { <pending> }
Promise { <pending> }
Promise { <pending> }
```
0.1초도 안돼서 콘솔에 위 내용이 모두 출력됩니다.
3초 후에 3이라는 리턴 값이 전달되지만 이미 console.log()는 수행되었기 때문에 3은 출력 결과에서 확인할 수 없습니다.

### 3.5 동기 비동기 특징, 예시

동기는 순차적으로 실행되기 때문에 어떻게 실행될 것인지 파악하는 게 굉장히 쉽습니다. 하지만 결과가 반환될 때까지 아무것도 못하고 대기해야합니다.
비동기는 거의 동시에 여러 가지 task를 수행하기 때문에 혼란스럽지만 훨씬 빠른 속도로 수행됩니다.

한 예시로, 비동기는 브라우저에서 많이 사용되고 있습니다.
만약 이미지 데이터는 불러오는데 10초가 걸리고 텍스트 데이터는 불러오는데 1초도 안걸린다고 해봅시다. 동기 방식로 이미지를 먼저 요청하고 응답은 받은 이후에 텍스트를 요청한다면 10초동안 아무것도 볼 수 없어서 답답할 것입니다. 반대로 비동기 방식로 리소스를 요청한다면 아직 이미지는 뜨지 않았지만 텍스트로 내용을 미리 짐작할 수 있을 것입니다.
비동기 방식을 사용했을 때 사용자는 반응성이 빠르다고 느낄 것입니다.

### 3.6 async, await: promise 비동기 개선

거슬러 거슬러 올라와서 본 질문이었던 async, await가 왜 더 개선된 방식인지 코드를 비교하면서 알아봅시다.
```js
someMethod()
  .then((result) => {
    console.log(result);
    return someMethod(); 
  })
  .then((result) => {
    console.log(result);
    return someMethod();
  })
  .then((result) => {
    console.log(result);
  });
```

```js
(async () => {
  console.log(await someMethod());
  console.log(await someMethod());
  console.log(await someMethod());
})();
```

두 코드는 모두 someMethod()를 3번 호출하고 있는데 someMethod()의 리턴 값인 3이 3번 콘솔에 출력되고 이 프로그램이 완료되기 위해서는 최소 9초의 시간이 걸립니다.

두 코드 중 어떤 코드가 가독성이 좋을까요? 
then, arrow function, return이 생략된 후자가 훨씬 깔끔하고 한 눈에 무엇을 하려는지 읽을 수 있습니다.

async, await 함수를 사용하면 비동기 함수를 마치 동기 함수처럼 사용할 수 있습니다.

### 3.7 정리

비동기 작업을 요청했다면 반환된 내용을 사용해야 하는데, 비동기 작업이 끝나 결과가 반환되었을 때를 다루기 위해서 앞서 설명한 Promise가 등장했습니다.

더 나아가 then, function, return 문을 감추어 가독성을 높이기 위해 async, await가 등장했습니다.

## 4. 코드 이해하기

비동기 Promise 구현 코드를 이해하기 위한 대부분의 지식을 배웠기 때문에 빠르게 살펴볼 수 있습니다.

### 4.1 resolve(성공)한 promise를 then으로 확인하는 과정 이해하기

```js
console.log("Start");
(async () => {
  console.log("return value: " await someMethod());
})();
```
이 코드를 실행하면 다음과 같이 출력됩니다.

```
Start
MyPromise 생성자 실행
then() 실행
this.callbackWhenResolved에 resolveCallback 등록
this.callbackWhenCaught에 rejectCallback 등록
MyPromise 생성자에 넘기는 콜백 함수에서 resolve() 실행 시점을 3000ms 후로 지정
resolve() 실행해 callback 함수가 실행됨
delay(3000), 즉 3초 후 출력됨
return value: 3
```

**왜 then이 먼저 실행되었을까요?**

delay 함수에서는 MyPromise를 생성할 때 콜백 함수를 넘겨주고 있습니다. constructor의 callback은 아래 함수를 뜻합니다.
```js
(resolve, reject) => { 
  process.stdout.write("MyPromise 생성자에 넘기는 콜백 함수에서 ");
  if (durationInMillis < 0) {
    reject(new Error(`Duration cannot be less than 0 but given ${durationInMillis}.`));
    return;
  }
  console.log("resolve() 실행 시점을 " + durationInMillis + "ms 후로 지정");
  setTimeout(() => {
    resolve();
  }, durationInMillis);
}
```

MyPromise의 생성자 내용을 이어서 보면 
```js
constructor(callback) {
  console.log("MyPromise 생성자 실행");
  this.callbackWhenResolved = null;
  this.callbackWhenCaught = null;

  setTimeout(() => {
    callback(
      (value) => {
        this.resolve(value);
      },
      (value) => {
        this.reject(value);
      }
    )
  });
}
```

0초 후라는 트릭을 사용해 then()이 먼저 실행해 함수를 등록한 다음에 constructor의 callback 함수를 실행하도록 구현했습니다.

then()에서는 this.callbackWhenResolved에 callback 함수를 등록하는 일을 합니다. 함수가 등록되어 있어야 resolve를 호출했을 때 this.callbackWhenResolved를 사용할 수 있기 때문에 callback 함수 (즉, durationInMillis로 판단해 resolve 또는 reject를 실행하는 함수)보다 먼저 실행되어야 합니다. 그래서 `setTimeout(code, 0);`을 사용했습니다.

참고로, [setTimeout](https://developer.mozilla.org/ko/docs/Web/API/setTimeout)의 2번째 파라미터에 delay할 ms를 지정할 수 있는데 delay paramter를 생략하거나 0으로 설정하면 다음 이벤트 사이클에 실행하도록 합니다. 이를 트릭을 사용하였습니다.

멤버 변수를 초기화하고 then()을 먼저 실행시키고 callback을 실행시키는데 MyPromise 클래스에서 구현한 this.resolve()와 this.reject() 메서드를 callback의 인자로 넘겨주고 있습니다.

-----
**여전히 의문이 남아있나요? 무슨 함수가 등록된다는 것인가요? 그래서 왜 then이 먼저 실행되나요? then을 누가 호출해주고 있나요?**

사실 현재 코드에서는 delay 함수에서 받은 promise를 
1. then이 아닌 try ~ catch 문으로 확인하고 있고 
2. delay 함수 내에서 resolve() 호출 시 아무 인자를 넘겨주고 있지 않아 대체 어떤 함수가 등록된다는 말인지 이해가 안 갈 수 있습니다. 

someMethod를 다음과 같이 변경해보겠습니다.
```js
const someMethod = async () => {
  await delay(3000)
    .then(() => {
      console.log("then test");
    });
  return 3;
};
```
delay 함수는 MyPromise를 생성해서 리턴하는 것이 전부입니다. 그런데 MyPromise 생성자 안에서 갑자기 setTimeout()을 호출해 callback 실행은 다음 이벤트 사이클 때 하라고 합니다. 그러면 바로 위 코드에서 생성자 로직을 수행하다 만 MyPromise 객체가 리턴되고 then()를 호출하게 됩니다. 네. then이 이 때 호출됩니다. 그리고나서 미뤄두었던 callback이 실행되는 것입니다.

.then()으로 명시적으로 호출하지 않아도 promise가 리턴되면 then이 호출됩니다.

MyPromise에서는 then이 인자를 2개를 가지고 있는데 someMethod에서는 then에 resolve되었을 때 실행할 첫 번째 함수만 인자로 전달하고 있습니다.
then이 실행될 때 resolveCallback.toString()으로 출력해보면 this.callbackWhenResolved에 `() => { console.log("then test"); }`가 등록되는 것을 볼 수 있습니다.
만약 someMethod then의 두 번째에도 callback 함수를 넘겨준다면 this.callbackWhenCaught에도 작성한 함수가 등록되는 것입니다.

본론으로 돌아와서 마무리를 짓겠습니다.

-----

```js
class 
  resolve(value) {
    console.log("resolve 함수 실행");
    if (this.callbackWhenResolved) {
      this.callbackWhenResolved(value);
    }
  }
```
callback 함수에서는 durationInMillis가 0 이상인 3000 이므로 3000ms가 지나고 `resolve();`가 수행됩니다.
생성된 MyPromise 객체에서 then()이 먼저 실행돼 this.callbackWhenResolved에 함수가 잘 등록된 상태에서 resolve 함수를 호출한 것입니다.

```js
const someMethod = async () => {
  try {
    await delay(3000);
    console.log("delay(3000), 즉 3초 후 출력됨");
  } catch (delayError) {
    console.log(delayError);
  }
  return 3;
};
```
delay 함수에 0 이상인 3000을 인자로 잘 넘겨주었기 때문에 delay(3000) 비동기 함수가 잘 완료된 이후에 "delay(3000), 즉 3초 후 출력됨" 을 출력하고 3을 반환해 return value: 3이 출력됩니다.

### 4.2 reject(실패)한 promise를 try~catch로 확인하는 과정 이해하기

wrongMethod()를 호출해서 reject()를 호출하고 error 객체를 전달하여 catch에서 전달받은 error를 확인해보겠습니다.

```js
(async () => {
  console.log("return value: " + await wrongMethod());
})();
```

호출하면 다음과 같은 결과를 확인할 수 있습니다.

```
Start
MyPromise 생성자 실행
then() 실행
this.callbackWhenResolved에 resolveCallback set됨
this.callbackWhenCaught에 rejectCallback set됨
MyPromise 생성자에 넘기는 콜백 함수에서 reject() 실행 시점을 지금 바로로 지정
reject() 실행해 callback 함수가 실행됨
wrongMethod()에서 error를 catch함
Error: Duration cannot be less than 0 but given -500.
    at ~/promise.js:8:9
    at Timeout._onTimeout (~/promise.js:28:7)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
return value: -5
```

delay 함수에 -500을 인자로 전달합니다.

MyPromise 생성자가 실행되고 0초 후 라는 트릭이 있는데 이 함수로 인해 마치 비동기 작업으로 여겨져서 callback()을 수행하기 전에 then()이 먼저 호출됩니다. 이 때 callbackWhenResolved와 callbackWhenCaught 멤버 변수에 각각의 callback이 set됩니다.

이후에 생성자 안의 callback 함수에 MyPromise의 resolve()와 reject() 메서드를 인자로 넘겨줍니다. 이 때, resolve()의 this.callbackWhenResolved에는 함수가 지정되어 있는 상태입니다. reject()와 관련된 this.callbackWhenCaught도 로그에 보이듯이 마찬가지로 함수가 등록되었습니다. then()이 이전에 호출되었기 때문입니다. 

callback 함수에서 -500은 0보다 작기 때문에 `reject(new Error(`Duration ~`));` 를 호출합니다. reject 함수에 생성된 error 객체를 전달합니다.
reject 함수는 아래 정의된 함수를 뜻하는데, 주의해서 보아야 할 점은 value를 파라미터로 받아서 다시 인자로 넘겨주고 있습니다.

```js
reject(value) {
  console.log("비동기 처리(0초 후로 비동기 흉내냄) 후 reject() 실행해 callback 함수가 실행됨");
  if (this.callbackWhenCaught) {
    this.callbackWhenCaught(value);
  }
} 
```

그래서 이후 wrongMethod 안에서 catch의 delayError 파라미터로 error 객체를 전달받아 정상적으로 출력한 뒤 -5를 반환합니다.

### 4.3 promise의 catch() 실행 해보기

**마지막으로 catch() 는 왜 실행되지 않을까요?**

현재, callbackWhenResolved 뿐만 아니라 callbackWhenCaught 멤버 변수도 then에서 함수를 등록하고 있기 때문입니다. promise 표준에서도 then 1개만 존재한다고 합니다.

구현한 것을 확인하고 싶다면 이렇게 사용할 수 있습니다.
```js
delay(-500)
  .catch((e) => {
    console.log(e + '\n' + "delay(-500)은 catch됨")
  });
```
이런 결과를 얻을 수 있습니다.
```
MyPromise 생성자 실행
catch() 실행
MyPromise 생성자에 넘기는 콜백 함수에서 reject() 실행 시점을 지금 바로로 지정
reject() 실행해 callback 함수가 실행됨
Error: Duration cannot be less than 0 but given -500.
delay(-500)은 catch됨
```

catch 함수의 callback으로 아래 함수가 callbackWhenCaught 멤버 변수에 등록됩니다. 그래서 error가 출력되고 있습니다.

```js
(e) => {
    console.log(e + '\n' + "delay(-500)은 catch됨")
  }
```

